CREATE TABLE contas_pj (
                           id CHAR(36) PRIMARY KEY,
                           cnpj VARCHAR(18) NOT NULL UNIQUE,
                           senha VARCHAR(255) NOT NULL,
                           faturamento_mensal DOUBLE NOT NULL,
                           porte VARCHAR(255) NOT NULL,
                           capital_social DOUBLE,
                           data_de_abertura VARCHAR(10) NOT NULL,
                           fantasia VARCHAR(255),
                           natureza_juridica VARCHAR(255),
                           status_solicitacao VARCHAR(20),
                           agencia INT NOT NULL,
                           numero_conta INT NOT NULL,
                           logradouro VARCHAR(255) NOT NULL,
                           numero VARCHAR(10) NOT NULL,
                           complemento VARCHAR(255),
                           bairro VARCHAR(255) NOT NULL,
                           cidade VARCHAR(255) NOT NULL,
                           estado VARCHAR(2) NOT NULL,
                           cep VARCHAR(9) NOT NULL,
                           pais VARCHAR(255) NOT NULL,
                           INDEX idx_status (status_solicitacao) USING BTREE
);
